import {
  Code,
  Database,
  Server,
  Globe,
  GitBranch,
  Container,
  Cloud,
  Flame,
  Layers,
  FileCode,
  Palette,
  Zap,
  Settings,
  Box,
} from 'lucide-vue-next'

export const TECH_ICON_MAP = {
  JavaScript: Code,
  TypeScript: FileCode,
  'Vue.js': Layers,
  React: Zap,
  'Node.js': Server,
  Express: Server,
  MongoDB: Database,
  PostgreSQL: Database,
  Python: Code,
  PHP: Globe,
  HTML: Globe,
  CSS: Palette,
  Git: GitBranch,
  Docker: Container,
  AWS: Cloud,
  Firebase: Flame,
  Laravel: Settings,
  'Nuxt.js': Box,
}

export const PROGRAMMING_STATS = [
  {
    name: 'JavaScript/TypeScript',
    percentage: 85,
    color: '#f7df1e',
    category: 'Frontend/Backend',
    years: 3,
    projects: 10,
    description: 'Primary language for full-stack development with modern frameworks and libraries.',
    tags: ['ES6+', 'Async/Await', 'TypeScript', 'Node.js'],
  },
  {
    name: 'Vue.js',
    percentage: 80,
    color: '#4fc08d',
    category: 'Frontend Framework',
    years: 3,
    projects: 25,
    description: 'Preferred frontend framework for building reactive and component-based applications.',
    tags: ['Composition API', 'Vuex', 'Vue Router', 'Nuxt.js'],
  },
  {
    name: 'React',
    percentage: 65,
    color: '#61dafb',
    category: 'Frontend Framework',
    years: 3,
    projects: 20,
    description: 'Extensive experience in building scalable React applications with modern patterns.',
    tags: ['Hooks', 'Redux', 'Next.js', 'React Native'],
  },
  {
    name: 'Node.js',
    percentage: 88,
    color: '#339933',
    category: 'Backend Runtime',
    years: 3,
    projects: 15,
    description: 'Server-side JavaScript development with Express, APIs, and microservices.',
    tags: ['Express.js', 'REST APIs', 'GraphQL', 'Microservices'],
  },
  {
    name: 'Python',
    percentage: 40,
    color: '#3776ab',
    category: 'Backend/Data Science',
    years: 2,
    projects: 3,
    description: 'Backend development, automation scripts, and data analysis projects.',
    tags: ['Django', 'Flask', 'Pandas', 'Automation'],
  },
  {
    name: 'PHP',
    percentage: 84,
    color: '#777bb4',
    category: 'Backend Language',
    years: 3,
    projects: 20,
    description: 'Web development with modern PHP frameworks and content management systems.',
    tags: ['Laravel', 'Lumen', 'WordPress', 'Composer'],
  },
  {
    name: 'MySQL/PostgreSQL',
    percentage: 82,
    color: '#336791',
    category: 'Database',
    years: 3,
    projects: 35,
    description: 'Database design, optimization, and complex query development.',
    tags: ['Query Optimization', 'Database Design', 'Migrations', 'Indexing'],
  },
  {
    name: 'MongoDB',
    percentage: 62,
    color: '#47a248',
    category: 'NoSQL Database',
    years: 2,
    projects: 5,
    description: 'NoSQL database development with aggregation pipelines and schema design.',
    tags: ['Aggregation', 'Mongoose', 'Atlas', 'Indexing'],
  },
]

export const TECH_STACK_ROW1 = ['JavaScript', 'TypeScript', 'Vue.js', 'React', 'Node.js', 'Express']
export const TECH_STACK_ROW2 = ['MongoDB', 'PostgreSQL', 'Python', 'PHP', 'HTML', 'CSS']
export const TECH_STACK_ROW3 = ['Git', 'Docker', 'AWS', 'Firebase', 'Laravel', 'Nuxt.js']

export const PROJECTS = [
  {
    id: 1,
    name: 'Weather Gaul App',
    description: 'Weather forecasts with map integration',
    tech: ['React', 'Leaflet', 'OpenWeatherMap API', 'Fully Functional'],
    image: new URL('../assets/programming/weather-gaul-app.png', import.meta.url).href,
  },
  {
    id: 2,
    name: 'Late Recapitulation',
    description: "Student's presence manager with VueJS and Laravel",
    tech: ['Vue', 'Laravel', 'Vuetify', 'MySQL', 'Fully Functional'],
    image: new URL('../assets/programming/late-recapitulation.png', import.meta.url).href,
  },
  {
    id: 3,
    name: 'Ticketing App',
    description: 'Booking simulation mobile application',
    tech: ['Flutter', 'Firebase', 'Fully Functional'],
    image: new URL('../assets/programming/ticketing-app.png', import.meta.url).href,
  },
  {
    id: 4,
    name: 'Makan Cuy',
    description: 'An award-winning LKS project that won first place, a food E-Commerce web application',
    tech: ['Vue', 'Vuetify', 'Lumen', 'MySQL', 'Fully Functional', 'Blind Coded'],
    image: new URL('../assets/programming/makan-cuy.png', import.meta.url).href,
  },
  {
    id: 5,
    name: 'Football Gaul',
    description: '2D football game I made with Javascript',
    tech: ['Native Javascript'],
    image: new URL('../assets/programming/football-wow.png', import.meta.url).href,
  },
  {
    id: 6,
    name: 'Nigmagrid Company Profile',
    description: 'Company profile website for Nigmagrid, built with Laravel.',
    tech: ['Laravel', 'Fully Functional'],
    image: new URL('../assets/programming/nigmagrid-company-profile.png', import.meta.url).href,
  },
  {
    id: 7,
    name: 'Nigma Risk',
    description: 'A risk management application built with Vue, Laravel, Vuetify, and Material Design.',
    tech: ['Vue', 'Laravel', 'Vuetify', 'Material Design', 'Fully Functional'],
    image: new URL('../assets/programming/nigma-risk.png', import.meta.url).href,
  },
  {
    id: 8,
    name: 'Investor Relation Portal',
    description: 'An application portal for investor relations, built with Laravel.',
    tech: ['Laravel', 'Fully Functional'],
    image: new URL('../assets/programming/investor-relation-portal.png', import.meta.url).href,
  },
  {
    id: 9,
    name: 'Amiga Plastik Management App',
    description: 'A management application for a plastic factory, built with Laravel and fully functional.',
    tech: ['Laravel', 'Fully Functional'],
    image: new URL('../assets/programming/amiga-plastik.png', import.meta.url).href,
  },
  {
    id: 10,
    name: 'WIKA Beton ManRisk',
    description: 'A risk management system for the state-owned enterprise client WIKA Beton, built with Laravel and fully functional.',
    tech: ['Laravel', 'Fully Functional'],
    image: new URL('../assets/programming/wika-manrisk.png', import.meta.url).href,
  },
  {
    id: 11,
    name: 'Gaul Chatting App',
    description: 'A real-time chatting application leveraging Next.js for the frontend, Golang for the backend, and WebSocket for real-time communication. Hosted on AWS using a three-tier architecture for scalability and reliability.',
    tech: ['Next.js', 'Golang', 'WebSocket', 'UI Slicing', 'AWS'],
    image: new URL('../assets/programming/gaul-chatting-app.png', import.meta.url).href,
  },
]
